### ISSUE TITLE
Other silpion roles reference silpion.util, but Ansible Galaxy has only groover.util

### ISSUE THREAD

**Issue by matevarga** [silpion/ansible-util#4]
Do you plan to install the roles in galaxy under the new (?) name in the near future? I'd like to use some of the roles (java and tomcat), but at the moment I need to fork them as galaxy-based dependency resolution doesn't work.

Thanks.

**Comment by AMeng** [comment]
As a workaround until this is resolved, you can tell `ansible-galaxy` to rename roles during installation. In my `requirements.yml` file I have:

```yaml
- src: groover.tomcat
  version: 1.1.1

- src: groover.util
  name: silpion.util
  version: 1.1.0
```
